FROM debezium/connect:2.3.0.Final

ADD java.security /etc/java/java-11-openjdk/java-11-openjdk-11.0.18.0.10-1.fc37.x86_64/conf/security/java.security
ADD java.config /etc/crypto-policies/back-ends/java.config
