services:
  debezium:
    image: local/debezium:2.3.0
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS}
      - GROUP_ID=${GROUP_ID}
      - CONFIG_STORAGE_TOPIC=${CONFIG_STORAGE_TOPIC}
      - OFFSET_STORAGE_TOPIC=${OFFSET_STORAGE_TOPIC}
      - STATUS_STORAGE_TOPIC=${STATUS_STORAGE_TOPIC}
      - CONNECT_KEY_CONVERTER=${CONNECT_KEY_CONVERTER}
      - CONNECT_VALUE_CONVERTER=${CONNECT_VALUE_CONVERTER}
      - CONNECT_INTERNAL_KEY_CONVERTER=${CONNECT_INTERNAL_KEY_CONVERTER}
      - CONNECT_INTERNAL_VALUE_CONVERTER=${CONNECT_INTERNAL_VALUE_CONVERTER}
      - CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE=${CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE}
      - CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE=${CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE}
      - CONNECT_SECURITY_PROTOCOL=${CONNECT_SECURITY_PROTOCOL}
      - CONNECT_SASL_MECHANISM=${CONNECT_SASL_MECHANISM}
      - CONNECT_SASL_JAAS_CONFIG=${CONNECT_SASL_JAAS_CONFIG}
      - CONNECT_PRODUCER_SECURITY_PROTOCOL=${CONNECT_PRODUCER_SECURITY_PROTOCOL}
      - CONNECT_PRODUCER_SASL_MECHANISM=${CONNECT_PRODUCER_SASL_MECHANISM}
      - CONNECT_PRODUCER_SASL_JAAS_CONFIG=${CONNECT_PRODUCER_SASL_JAAS_CONFIG}
      - CONNECT_CONSUMER_SECURITY_PROTOCOL=${CONNECT_CONSUMER_SECURITY_PROTOCOL}
      - CONNECT_CONSUMER_SASL_MECHANISM=${CONNECT_CONSUMER_SASL_MECHANISM}
      - CONNECT_CONSUMER_SASL_JAAS_CONFIG=${CONNECT_CONSUMER_SASL_JAAS_CONFIG}
    ports:
      - 8083:8083
